const MIMETtypes = [
{application:"MPEG movie file", type:"video",	mimetype:"video/mpeg", 	ext:"mpe"},
{application:"MPEG movie file", type:"video",	mimetype:"video/mpeg", 	ext:"mpeg"},
{application:"MPEG movie file", type:"video",	mimetype:"video/mpeg", 	ext:"mpg"},
{application:"MPEG-2 video stream", type:"video",	mimetype:"video/mpeg", ext:"mpv2"},
{application: "MPEG-2 audio file", type:"video",	mimetype: "video/mpeg", 	ext:"mpa"},
{application:"MPEG-4", type:"video",	mimetype:"video/mp4", 	ext:"mp4"},
{application:"Apple QuickTime movie", type:"video",	mimetype:"video/quicktime", 	ext:"mov"},
{application:"Apple QuickTime movie", type:"video",	mimetype:"video/quicktime", 	ext:"qt"},
{application:"Logos library system file", type:"video",	mimetype:"video/x-la-asf", 	ext:"lsf"},
{application:"streaming media shortcut", type:"video", 	mimetype:"video/x-la-asf", 	ext:"lsx"},
{application:"advanced systems format file", type:"video",	mimetype:"video/x-ms-asf", 	ext:"asf"},
{application:"ActionScript remote document", type:"video",	mimetype:"video/x-ms-asf", 	ext:"asr"},
{application:"Microsoft ASF redirector file", type:"video",	mimetype:"video/x-ms-asf", 	ext:"asx"},
{application:"audio video interleave file", type:"video",	mimetype:"video/x-msvideo", 	ext:"avi"},
{application:"Apple QuickTime movie", type:"video",	mimetype:"video/x-sgi-movie", 	ext:"movie"},
{application:"Bitmap", type:"image", mimetype:"image/bmp", ext:"bmp"},
{application:"compiled source code", type:"image", mimetype:"image/cis-cod", ext:"cod"},
{application:"graphic interchange format", type:"image", mimetype:"image/gif", ext:"gif"},
{application:"image file", type:"image",	mimetype:"image/ief",	ext:"ief"},
{application:"Bitmap",  type:"image",	mimetype:"image/bmp", 	ext:"bmp"},
{application:"compiled source code", type:"image", mimetype:"image/cis-cod", ext:"cod"},
{application:"graphic interchange format",  type:"image", mimetype:"image/gif", ext:"gif"},
{application:"image file",  type:"image",	mimetype:"image/ief ", ext:"ief"},
{application:"Bitmap", type:"image", mimetype:"image/bmp", ext:"bmp"},
{application:"compiled source code",  type:"image", mimetype:"image/cis-cod", 	ext:"cod"},
{application:"graphic interchange format",  type:"image",	mimetype:"image/gif", ext:"gif"},
{application:"image file",  type:"image", mimetype:"image/ief",	ext:"ief"},
{application:"JPEG image",  type:"image", mimetype:"image/jpeg", ext:"jpe"},
{application:"JPEG image",  type:"image", mimetype:"image/jpeg", ext:"jpeg"},
{application:"JPEG image",  type:"image", mimetype:"image/jpeg", ext:"jpg"},
{application:"JPEG file interchange format",  type:"image", mimetype:"image/pipeg", ext:"jfif"},
{application:"scalable vector graphic",  type:"image", mimetype:"image/svg+xml", ext:"svg"},
{application:"TIF image",  type:"image", mimetype:"image/tiff", ext:"tif"},
{application:"TIF image",	 type:"image", mimetype:"image/tiff",	ext:"tiff"},
{application:"Sun raster graphic",  type:"image", mimetype:"image/x-cmu-raster", ext:"ras"},
{application:"Corel metafile exchange image file",  type:"image", mimetype:"image/x-cmx", ext:"cmx"},
{application:"icon",  type:"image", mimetype:"image/x-icon", ext:"ico"},
{application:"portable any map image",  type:"image", mimetype:"image/x-portable-anymap", ext:"pnm"},
{application:"portable bitmap image",  type:"image", mimetype:"image/x-portable-bitmap", ext:"pbm"},
{application:"portable graymap image",  type:"image", mimetype:"image/x-portable-graymap", ext:"pgm"},
{application:"portable pixmap image", mimetype:"image/x-portable-pixmap", ext:"ppm"},
{application:"RGB bitmap",  type:"image", mimetype:"image/x-rgb", ext:"rgb"},
{application:"X11 bitmap",  type:"image", mimetype:"image/x-xbitmap", ext:"xbm"},
{application:"X11 pixmap",  type:"image", mimetype:"image/x-xpixmap", ext:"xpm"},
{application:"X-Windows dump image", 	 type:"image", mimetype:"image/x-xwindowdump", 	ext:"xwd"},
{application:"JPEG image",	 type:"image", mimetype:"image/jpeg", 	ext:"jpe"},
{application:"JPEG image", 	 type:"image", mimetype:"image/jpeg", 	ext:"jpeg"},
{application:"JPEG file interchange format", 	 type:"image", mimetype:"image/pipeg", ext:"jfif"},
{application:"scalable vector graphic",  type:"image", mimetype:"image/svg+xml", 	ext:"svg"},
{application:"TIF image",  type:"image", mimetype:"image/tiff", 	ext:"tif"},
{application:"TIF image",  type:"image", mimetype:"image/tiff", 	ext:"tiff"},
{application:"Sun raster graphic", 	 type:"image", mimetype:"image/x-cmu-raster", 	ext:"ras"},
{application:"Corel metafile exchange image file",  type:"image",	mimetype:"image/x-cmx", 	ext:"cmx"},
{application:"icon",  type:"image", mimetype:"image/x-icon", ext:"ico"},
{application:"portable any map image",  type:"image", mimetype:"image/x-portable-anymap", ext:"pnm"},
{application:"portable bitmap image", 	 type:"image", mimetype:"image/x-portable-bitmap",	ext:"pbm"},
{application:"portable graymap image",  type:"image",	mimetype:"image/x-portable-graymap", 	ext:"pgm"},
{application:"portable pixmap image",  type:"image",	mimetype:"image/x-portable-pixmap", ext:"ppm"},
{application:"RGB bitmap",  type:"image", mimetype:"image/x-rgb", ext:"rgb"},
{application: "Portable Network Graphics", type: "image", mimetype: "image/png", ext:"png"},
{application:"X11 bitmap",  type:"image", mimetype:"image/x-xbitmap", ext:"xbm"},
{application:"X11 pixmap",  type:"image", mimetype:"image/x-xpixmap", ext:"xpm"},
{application:"X-Windows dump image",  type:"image", mimetype:"image/x-xwindowdump", ext:"xwd"},
{application:"JPEG image", type:"image", mimetype:"image/jpeg", ext:"jpe"},
{application:"JPEG image", type:"image", mimetype:"image/jpeg", ext:"jpeg"},
{application:"JPEG file interchange format",  type:"image", mimetype:"image/pipeg", ext:"jfif"},
{application:"scalable vector graphic",  type:"image", mimetype:"image/svg+xml", 	ext:"svg"},
{application:"TIF image",  type:"image",	mimetype:"image/tiff", ext:"tif"},
{application:"TIF image",  type:"image",	mimetype:"image/tiff", ext:"tiff"},
{application:"Sun raster graphic",  type:"image",	mimetype:"image/x-cmu-raster", ext:"ras"},
{application:"Corel metafile exchange image file",  type:"image", mimetype:"image/x-cmx", 	ext:"cmx"},
{application:"icon", 	 type:"image", mimetype:"image/x-icon", 	ext:"ico"},
{application:"portable any map image", type:"image", mimetype:"image/x-portable-anymap", ext:"pnm"},
{application:"portable bitmap image",  type:"image", mimetype:"image/x-portable-bitmap", ext:"pbm"},
{application:"portable graymap image",  type:"image", mimetype:"image/x-portable-graymap", ext:"pgm"},
{application:"portable pixmap image",  type:"image",	mimetype:"image/x-portable-pixmap", 	ext:"ppm"},
{application:"RGB bitmap",  type:"image", mimetype:"image/x-rgb", ext:"rgb"},
{application:"X11 bitmap",  type:"image", mimetype:"image/x-xbitmap", ext:"xbm"},
{application:"X11 pixmap",  type:"image", mimetype:"image/x-xpixmap", ext:"xpm"},
{application:"X-Windows dump image",  type:"image", mimetype:"image/x-xwindowdump", ext:"xwd"}
]


export default MIMETtypes











