const HANDLE ={

    LOAD: 'LOAD_VIDEO',
    PLAY_PAUSE: 'PLAY_PAUSE_VIDEO',
    STOP: 'STOP_VIDEO',
    TOGGLE_CONTROLS: 'TOGGLE_CONTROLS_VIDEO',
    LIGHT: 'LIGHT_VIDEO',
    TOGGLE_LOOP: 'TOGGLE_LOOP_VIDEO',
    VOLUME_CHANGE: 'VOLUME_CHANGE_VIDEO',
    TOGGLE_MUTED: 'TOGGLE_MUTED_VIDEO',
    SET_PLAY_BACK_RATE: 'SET_PLAY_BACK_RATE_VIDEO',
    TOGGLE_PIP:'TOGGLE_PIP_VIDEO',
    PLAY: 'PLAY_VIDEO',
    ENABLE_PIP: 'ENABLE_PIP_VIDEO',
    DISABLE_PIP: 'DISABLE_PIP_VIDEO',
    PAUSE: 'PAUSE_VIDEO',
    SEEKMOUSE_DOWN: 'SEEKMOUSE_DOWN_VIDEO',
    SEEK_CHANGE: 'SEEK_CHANGE_VIDEO',
    SEEK_MOUSEUP: 'SEEK_MOUSEUP_VIDEO',
    PROGRESS: 'PROGRESS_VIDEO',
    ENDED: 'ENDED_VIDEO',
    DURATION: 'DURATION_VIDEO',
    FULLSCREEN: 'FULLSCREEN_VIDEO',
    SET_REF: 'SET_VIDEO_REF_VIDEO'
}


export default HANDLE