const HANDLE ={

    LOAD: 'LOAD',
    PLAY_PAUSE: 'PLAY_PAUSE',
    STOP: 'STOP',
    TOGGLE_CONTROLS: 'TOGGLE_CONTROLS',
    LIGHT: 'LIGHT',
    TOGGLE_LOOP: 'TOGGLE_LOOP',
    VOLUME_CHANGE: 'VOLUME_CHANGE',
    TOGGLE_MUTED: 'TOGGLE_MUTED',
    SET_PLAY_BACK_RATE: 'SET_PLAY_BACK_RATE',
    TOGGLE_PIP:'TOGGLE_PIP',
    PLAY: 'PLAY',
    ENABLE_PIP: 'ENABLE_PIP',
    DISABLE_PIP: 'DISABLE_PIP',
    PAUSE: 'PAUSE',
    SEEKMOUSE_DOWN: 'SEEKMOUSE_DOWN',
    SEEK_CHANGE: 'SEEK_CHANGE',
    SEEK_MOUSEUP: 'SEEK_MOUSEUP',
    PROGRESS: 'PROGRESS',
    ENDED: 'ENDED',
    DURATION: 'DURATION',
    FULLSCREEN: 'FULLSCREEN'
}


export default HANDLE