import apiActions from "../../../utils/asyncActionTypes";


const {TYPES, API} = apiActions

const galleryConstants = {
    ...TYPES("GALLERY"),
    PAGINATE_NEXT:'PAGINATE_NEXT',
    PAGINATE_PREV: 'PAGINATE_PREV',
    SET_ACTIVE_MEDIA_ID: 'SET_ACTIVE_MEDIA_ID',
    SHOW_MODAL: 'SHOW_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    API,
    SET_ACTIVE_ID: 'SET_ACTIVE_ID',
    ADD_MEDIA_FILTER: 'ADD_MEDIA_FILTER',
    REMOVE_MEDIA_FILTER: 'REMOVE_MEDIA_FILTER',
    REMOVE_ALL_MEDIA_FILTER: 'REMOVE_ALL_MEDIA_FILTER',
    ADD_FILTER_TAG: 'ADD_FILTER_TAG',
    REMOVE_FILTER_TAG: 'REMOVE_FILTER_TAG',
    REMOVE_ALL_FILTER_TAGS: 'REMOVE_ALL_FILTER_TAGS',
    SET_FILTER_BUTTON_ACTIVE: 'FILTER_BUTTON_ACTIVE',
    REMOVE_FILTER_BUTTON_INACTIVE: 'FILTER_BUTTON_INACTIVE',
    ADD_USER_TAGS: 'ADD_USER_TAGS',
    REMOVE_USER_TAGS: 'REMOVE_USER_TAGS',
    UPDATE_MEDIA: 'UPDATE_MEDIA'

}



export default galleryConstants